CREATE TABLE skill (
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	primary_name_id INTEGER,
	apparatus_id INTEGER 
		REFERENCES apparatus(id),
	level_id INTEGER  
		REFERENCES level(id),
	age_id INTEGER 
		REFERENCES age(id),
	priority_id INTEGER  
		REFERENCES priority(id),
	class_id INTEGER 
		REFERENCES class(id),
	action_id INTEGER  
		REFERENCES action(id),
	details TEXT,
	prerequisites TEXT,
	warm_up TEXT,
	video VARCHAR(2083)
	);

